import DAO.*;
import DBC.*;
import Objects.*;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class WalletTransferAmount extends javax.swing.JInternalFrame {

    /**
     * Creates new form WalletTransferAmount
     */
    public WalletTransferAmount() {
        initComponents();
           Receipt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransferAmount = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfrecipient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnsend = new javax.swing.JButton();
        Receipt = new javax.swing.JPanel();
        btnconfirmtransfer = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbltransfund = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblmywallet = new javax.swing.JLabel();
        lblsendcontnum = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblrecname = new javax.swing.JLabel();
        lblreccontnum = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        TransferAmount.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Recipient:");

        tfrecipient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204)));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Amount:");

        tfamount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204)));
        tfamount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfamountMouseClicked(evt);
            }
        });
        tfamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfamountActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Php");

        jLabel9.setText("You have Php ____ in your wallet.");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Note (Optional)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 204)));
        jScrollPane1.setViewportView(jTextArea1);

        btnsend.setBackground(new java.awt.Color(0, 102, 51));
        btnsend.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsend.setForeground(new java.awt.Color(255, 255, 255));
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        Receipt.setBackground(new java.awt.Color(255, 255, 255));
        Receipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 5));

        btnconfirmtransfer.setBackground(new java.awt.Color(0, 102, 51));
        btnconfirmtransfer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnconfirmtransfer.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirmtransfer.setText("Confirm");
        btnconfirmtransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmtransferActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Confirm Transfer Fund");

        lbltransfund.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        lbltransfund.setText("Php 1.00");

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Source");

        lblmywallet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblmywallet.setText("My Wallet");

        lblsendcontnum.setBackground(new java.awt.Color(0, 0, 0));
        lblsendcontnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblsendcontnum.setText("09898675");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmywallet)
                    .addComponent(lblsendcontnum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblmywallet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsendcontnum)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Destination");

        lblrecname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblrecname.setText("ngalan recipient");

        lblreccontnum.setBackground(new java.awt.Color(0, 0, 0));
        lblreccontnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblreccontnum.setText("09**-***-**09");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblrecname)
                    .addComponent(lblreccontnum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblrecname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblreccontnum))
                    .addComponent(jLabel17))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReceiptLayout = new javax.swing.GroupLayout(Receipt);
        Receipt.setLayout(ReceiptLayout);
        ReceiptLayout.setHorizontalGroup(
            ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ReceiptLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ReceiptLayout.createSequentialGroup()
                            .addGroup(ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ReceiptLayout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addGroup(ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbltransfund, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addGroup(ReceiptLayout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(btnconfirmtransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 78, Short.MAX_VALUE)))
                    .addGap(41, 41, 41)))
        );
        ReceiptLayout.setVerticalGroup(
            ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ReceiptLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbltransfund)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnconfirmtransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout TransferAmountLayout = new javax.swing.GroupLayout(TransferAmount);
        TransferAmount.setLayout(TransferAmountLayout);
        TransferAmountLayout.setHorizontalGroup(
            TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferAmountLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TransferAmountLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(tfrecipient)
                        .addComponent(jLabel10)
                        .addComponent(jScrollPane1)
                        .addGroup(TransferAmountLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(109, 109, 109)
                .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferAmountLayout.setVerticalGroup(
            TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferAmountLayout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfrecipient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TransferAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfamount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TransferAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TransferAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfamountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfamountMouseClicked

    }//GEN-LAST:event_tfamountMouseClicked

    private void tfamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfamountActionPerformed

    }//GEN-LAST:event_tfamountActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        String receiver   = tfrecipient.getText().trim();
        String amountText = tfamount.getText().trim();
        

        if (receiver.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a recipient username.");
            return;
        }
        if (amountText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter an amount.");
            return;
        }

        java.math.BigDecimal amount;
        try {
            amount = new java.math.BigDecimal(amountText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid amount entered.");
            return;
        }

        if (amount.compareTo(java.math.BigDecimal.ZERO) <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Amount must be greater than zero.");
            return;
        }

        long uid = session.getInstance().getCurrentUserId();
        transactionDAO tDAO = new transactionDAO();
        userWallet wallet = tDAO.readBalance(uid);
        userDAO uDAO = new userDAO();

        if (wallet == null || wallet.getRegularWallet().compareTo(amount) < 0) {
            JOptionPane.showMessageDialog(rootPane,
                "Insufficient balance. Available: ₱" +
                (wallet != null ? wallet.getRegularWallet() : "0"),
                "Insufficient Funds", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        String receiverContact = uDAO.getContactByUsername(receiver);
            if (receiverContact.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane,
                    "Recipient username \"" + receiver + "\" not found.",
                    "User Not Found", JOptionPane.ERROR_MESSAGE);
            return;
        }

         String senderContact = uDAO.getContactByUid(uid);
         String sender = uDAO.getUsernameByUid(uid);
         
         lbltransfund.setText("₱ " + amount.toPlainString());

         // Source row  → "My Wallet" + sender's contact number
         lblmywallet.setText(sender);
         lblsendcontnum.setText(senderContact);   // the contact number under "My Wallet"

         // Destination row → receiver username + receiver's contact number
         lblrecname.setText(receiver);
         lblreccontnum.setText(receiverContact);    // the contact number under the username

         Receipt.setVisible(true);

    }//GEN-LAST:event_btnsendActionPerformed

    private void btnconfirmtransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmtransferActionPerformed
        String receiver   = tfrecipient.getText().trim();
        String amountText = tfamount.getText().trim();

        String pin = JOptionPane.showInputDialog(rootPane, "Enter your PIN to confirm transfer:");
        if (pin == null || pin.trim().isEmpty()) return;

        long uid = session.getInstance().getCurrentUserId();
        userDAO uDAO = new userDAO();
        if (!uDAO.verifyPin(uid, pin.trim())) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect PIN.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.math.BigDecimal amount = new java.math.BigDecimal(amountText);
        transactionDAO tDAO = new transactionDAO();
        boolean ok = tDAO.transferFunds(uid, receiver, amount);

        if (ok) {
            JOptionPane.showMessageDialog(rootPane,
                "₱" + amount + " transferred to " + receiver + " successfully!");
            tfrecipient.setText("");
            tfamount.setText("");
            Receipt.setVisible(false);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane,
                "Transfer failed. Check that the recipient username exists.",
                "Transfer Failed", JOptionPane.ERROR_MESSAGE);
            Receipt.setVisible(false);
        }
    }//GEN-LAST:event_btnconfirmtransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Receipt;
    private javax.swing.JPanel TransferAmount;
    private javax.swing.JButton btnconfirmtransfer;
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblmywallet;
    private javax.swing.JLabel lblreccontnum;
    private javax.swing.JLabel lblrecname;
    private javax.swing.JLabel lblsendcontnum;
    private javax.swing.JLabel lbltransfund;
    private javax.swing.JTextField tfamount;
    private javax.swing.JTextField tfrecipient;
    // End of variables declaration//GEN-END:variables
}
